#!/usr/bin/env bash
#
# Copyright 2020 - 2024, Dave Slotter (W3DJS). All rights reserved.
# Copyright 2024 - 2026, HamPi contributors.
#
# Licensed under the GNU General Public License v3.0. See LICENSE.
#
# Builds HamPC inside a Xubuntu virtual machine, using the hosts_xubuntu_vm
# inventory instead of the default one. All arguments are passed through to
# ansible-playbook.
#
# Usage:
#     ./run_HamPi_playbook_xubuntu_vm [additional ansible-playbook arguments]
#

cd "$(dirname "$0")" || exit 1

export HAMPI_INVENTORY="hosts_xubuntu_vm"

exec ./run_HamPi_playbook "$@"
