#!/usr/bin/env bash
#
# Catches task structure that is valid YAML but wrong Ansible.
#
# The case that prompted this: five playbooks were generated by a shell
# script whose command substitution stripped a trailing newline, merging the
# last list entry into the following key:
#
#     with_items:
#       - build-essential
#       - libflxmlrpc-dev      retries: 5     <-- one line, not two
#
# That parses. It is a list whose last element is the mapping
# {'libflxmlrpc-dev      retries': 5}, so yamllint, ansible-lint and
# ansible-playbook --syntax-check all pass it. It fails only when the task
# runs, eight minutes into an image build, with
#
#     argument 'package' is of type dict and we were unable to convert to
#     list: <class 'dict'> cannot be converted to a list
#
# Nothing in this tree loops over a dict on purpose -- 108 literal-list loops
# and not one of them -- so any dict or list element is a defect.
#
# Offline and fast.

set -u
cd "$(dirname "$0")/.."

python3 - "$@" <<'PY'
import glob
import sys

import yaml


def tasks_of(doc):
    """Yield tasks from a playbook or a bare task list."""
    if not isinstance(doc, list):
        return
    for entry in doc:
        if not isinstance(entry, dict):
            continue
        if 'hosts' in entry or 'tasks' in entry:
            for key in ('tasks', 'pre_tasks', 'post_tasks', 'handlers'):
                for task in (entry.get(key) or []):
                    yield task
        else:
            yield entry


failures = []
loops = 0
files = 0

for path in sorted(glob.glob('tasks/*.yml') + glob.glob('library/*.yml')):
    try:
        doc = yaml.safe_load(open(path))
    except yaml.YAMLError as exc:
        failures.append(f'{path}: will not parse: {exc}')
        continue
    if not doc:
        continue
    files += 1
    for task in tasks_of(doc):
        if not isinstance(task, dict):
            continue
        name = task.get('name', '<unnamed>')
        for key in ('with_items', 'loop'):
            value = task.get(key)
            if not isinstance(value, list):
                continue
            loops += 1
            for item in value:
                if isinstance(item, (dict, list)):
                    failures.append(
                        f'{path}: task {name!r}: {key} element is a '
                        f'{type(item).__name__}, not a string: {item!r}'
                    )

print('Task structure')
print(f'  checked {loops} literal-list loops across {files} files')
if failures:
    for line in failures:
        print(f'  FAIL {line}')
    print(f'\n  {len(failures)} failed')
    sys.exit(1)
print('  ok   every loop element is a scalar')
print('\n  1 passed, 0 failed')
PY
